services:
  db:
    image: postgres:17.4
    container_name: churchmanager-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: churchmanager
